<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

 

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this ->load-> model('pesanan');
    }

    public function index()
    {
        $this->load->view('home');
        
    } 
      public function user1()
    {

      
       $data['kategori']=$this->pesanan->selectkategori();
       $data['deadline']=$this->pesanan->selectdeadline();
        $this->load->view('/utama',$data);
         //$this ->load-> model('pesanan');
        
    } 


  

    function tambah_pesan_aksi(){
        $data = array(
             'nama_pesanan' => $this->input->post( 'nama_pesanan'),
            'email_user' => $this->input->post('email_user'),
           'isi_pesan'  => $this->input->post('isi_pesan' ),
           
            'id_kategori' => $this->input->post('id_kategori'),
            'id_deadline' =>$this->input->post('id_deadline') 
        );
        $this->pesanan->tambahpesan($data);
        redirect(site_url('Home'));
    }

    
//--------
//------------------------------------
     
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */
 

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */